name: weahtr
channels:
  - conda-forge
#  - pytorch-nightly

dependencies:
# General python settings
  - python==3.8
  - conda
  - wheel
  - pip
# Data science / computer vision components
  - scikit-learn
  - matplotlib
  - scipy
  - numpy
  - pandas
  - opencv
# utilities
  - setuptools
  - requests
  - pyyaml
# ML components
  - pytorch-lightning
  - tiktoken
  - protobuf
  - albumentations
  - datasets
  - transformers
  - jiwer
# OCR components
  - pytesseract
  - tesseract
  - mittagessen::kraken
  - pip:
     - evaluate
     - torch
     - torchvision
     - nnutils-pytorch-cuda
     - pylaia
