name: weahtr
channels:
  - conda-forge
  - pytorch
  - nvidia
# ignore default due to
# subscription service shenanigans

dependencies:
# General python settings
  - python>=3.11
  - conda>=23.5.2
  - wheel
  - pip
# Data science / computer vision components
  - scikit-learn
  - matplotlib
  - scipy
  - numpy
  - pandas
  - opencv
# utilities
  - setuptools
  - requests
  - pyyaml
# ML components
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - tiktoken
  - protobuf
  - albumentations
  - datasets
  - transformers
  - jiwer
  - ultralytics # reconsider for deletion
# OCR components
  - easyocr
  - pytesseract
  - pip:
     - evaluate
