name: weahtr
channels:
  - conda-forge # to be OSS stay away from default

# functional PyLaia setup

dependencies:
# General python settings
  - python
  - conda
  - wheel
  - pip
# Data science / computer vision components
  - scikit-learn
  - matplotlib
  - scipy
  - numpy
  - pandas
  - opencv
# utilities
  - setuptools
  - requests
  - pyyaml
# ML components
  - pytorch-lightning
  - tiktoken
  - protobuf
  - albumentations
  - datasets
  - transformers
  - jiwer
  - shapely
  - coremltools
# OCR components
  - pytesseract
  - tesseract
  - pip:
     - evaluate
     - torch
     - torchvision
     - nnutils-pytorch-cuda
     - pylaia
