name: weahtr
channels:
  - conda-forge
  - pytorch
  - nvidia

dependencies:
  - python>=3.11
  - conda>=23.5.2
  - matplotlib
  - setuptools
  - requests
  - pandas
  - pip
  - transformers
  - wheel
  - scipy
  - numpy
  - opencv
  - easyocr
  - pytesseract
  - ultralytics
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pyyaml
